### ISSUE TITLE
can the repository update all the way?

### ISSUE THREAD

**Issue by joostshao** [knpuniversity/symfonycon-frontend#1]
can the repository update all the way?

**Comment by weaverryan** [comment]
@JoostShao Sorry I missed this early! What do you mean? Checkout the [assets-in-root](https://github.com/knpuniversity/symfonycon-frontend/tree/assets-in-root) branch, up to date with the latest evolutions.

Let me know if that's what you were looking for!

**Comment by joostshao** [comment]
I have builded it ,thanks.
Amazing frontend with sf2.

**Comment by weaverryan** [comment]
Cheers!
