### ISSUE TITLE
Creating new Event gives an 'Integrity constraint violation'

### ISSUE THREAD

**Issue by tlfbrito** [knpuniversity/symfonycon-frontend#9]
Every time I try to create a new Event I get this error:

`message: "An exception occurred while executing 'UPDATE yoda_user SET password = ? WHERE id = ?' with params [null, 4]:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null"
…}`

from: 

```
Request URL:http://localhost:8000/app_dev.php/create.json
Request Method:POST
Status Code:500 Internal Server Error
```

**Comment by weaverryan** [comment]
Hey @tiagobrito!

About the Event stuff, I just used that as a simple example app to show off the frontend stuff. If you want to see the real, updated version of the Event app, check out  https://github.com/knpuniversity/symfony2-series and the corresponding episodes at KnpUniversity: http://knpuniversity.com/screencast/tag/symfony

This will have the updated code with everything working.

Thanks!
